### PR TITLE
Converting all controller names to title case

### PR DESCRIPTION
**Pull request by Celeo**
I'm not currently running the entire site locally, so I haven't checked all the usage instances, but with the existing utility function, it's pretty simple.

### CODE REVIEW

**Comment by Celeo** [comment]
Whoops, committed the facility file replacement. Will undo.

**Review by Raajheer1 — APPROVED** [review]

**Review by dhawton — CHANGES_REQUESTED** [review]
Discussed with Raaj, this PR introduces errors for names like McScott or other names with multiple capitals.

**Comment by dhawton** [comment]
Also missing the actual helpers changes

**Comment by Celeo** [comment]
For names with multiple capital letters, I can either leave letters that aren't the first of each name alone, and folks who set their name to _all_ capitals will just be left alone, or can try poking around for a list of names and match against that. The first is easier, and probably less error-prone.

As for the `toTitleCase` function, it [already exists](https://github.com/adh-partnership/frontend/blob/main/src/utils/helpers.ts#L66-L75).

**Comment by dhawton** [comment]
> For names with multiple capital letters, I can either leave letters that aren't the first of each name alone, and folks who set their name to _all_ capitals will just be left alone, or can try poking around for a list of names and match against that. The first is easier, and probably less error-prone.
> 
> As for the `toTitleCase` function, it [already exists](https://github.com/adh-partnership/frontend/blob/main/src/utils/helpers.ts#L66-L75).

The design of this webstack is VATSIM is the source of truth for CID.. VATUSA and VATSIM combined are the source of truth for a controller's assigned region, division and subdivision... And VATSIM through VATUSA is the source of truth for names and emails. I would prefer to not have any deviation from the source of truth. This means a user whose name changes need only notify VATSIM and it'll filter down naturally and our data has no deviation from the source of truth. The only thing the webstack is truth on is certifications for a given CID.

**Comment by Celeo** [comment]
Gotcha, makes sense - the best way to "resolve" incorrectly capitalized names is for each user at the VATSIM level. Would, then, any attempt at changing capitalization be against the goals of the project?

**Comment by dhawton** [comment]
> Gotcha, makes sense - the best way to "resolve" incorrectly capitalized names is for each user at the VATSIM level. Would, then, any attempt at changing capitalization be against the goals of the project?

Correct... outside of certifications, the goal is to mirror VATSIM data.

**Pull request closed without merging**
